ALTER TABLE tasks ADD COLUMN user_id INTEGER;
ALTER TABLE tasks ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE tasks ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE tasks ADD COLUMN deleted_at TIMESTAMP;
