# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.20 AS object-build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build ./cmd/object/main.go

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=object-build-stage /main /main

EXPOSE 8081

USER nonroot:nonroot

ENTRYPOINT ["/main"]