# syntax=docker/dockerfile:1

FROM golang:1.20

WORKDIR /app

COPY . /app/
RUN go mod download

RUN mcdir -p bin/auth
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/auth ./cmd/auth

EXPOSE 8082

CMD ["/bin/auth"]
