# syntax=docker/dockerfile:1

FROM golang:1.20

WORKDIR /app

COPY . /app/
RUN go mod download

RUN mcdir -p bin/task
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/task ./cmd/task

EXPOSE 8080

CMD ["/bin/task"]
